dist: trusty
sudo: required
osx_image: xcode8.3
language: go

go:
  - 1.13.x
  - master
  - tip

os:
  - linux
  - osx

matrix:
  # It's ok to fail on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish.
  # Mark the test run green if the tests pass on the stable versions.
  fast_finish: true

env:
  - V=2.0.0

before_install:
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
  - CI_ARTIFACT="bazel--installer.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - if [[ "$V" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
  - if [[ "$V" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

install: true

notifications:
  email: false

script:
  - env GO111MODULE=on go build
  # Testing requires compiling protos so we use bazel for testing
  - bazel test //:go_default_test --test_output=all -coverprofile=coverage.txt -coverpkg=all -covermode=atomic
  # Generate coverage report
  - bazel coverage //:go_default_test
  - cp ./bazel-testlogs/go_default_test/coverage.dat coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
